language: java
script: ./gradlew build -s
jdk:
  - openjdk12
# Caching for Gradle files, prevents hitting Maven too much.
before_cache:
  - find /home/travis/.gradle/ . -name '*.lock' -print -exec rm -f {} \;
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Faster builds without sudo.
sudo: false
after_script:
  # Make sure to kill daemon
  - ./gradlew --stop
